@startuml
skinparam packageStyle rectangle
left to right direction

title Контекстная диаграмма системы ресторана «Махачкала»

rectangle "Система ресторана «Махачкала»" {
}

actor "Пользователь" as User
actor "Курьер" as Courier
actor "Администратор" as Admin

User --> "Система ресторана «Махачкала»" : делает заказ
Courier --> "Система ресторана «Махачкала»" : доставляет заказ
Admin --> "Система ресторана «Махачкала»" : управляет системой

@enduml
