@startuml
skinparam packageStyle rectangle
left to right direction

' Контекстная диаграмма
title Контекстная диаграмма системы ресторана «Махачкала»

rectangle 'Система ресторана «Махачкала»' {
}

actor Пользователь
actor Курьер
actor Администратор

Пользователь -->> Система ресторана «Махачкала» : делает заказ
Курьер -->> Система ресторана «Махачкала» : доставляет заказ
Администратор -->> Система ресторана «Махачкала» : управляет системой

@enduml
