@startuml
title Система ресторана «Махачкала»

actor Пользователь
participant "Ресторан «Махачкала»" as Ресторан

Пользователь -> Ресторан: Делает заказ
activate Ресторан
Ресторан -> Ресторан: Получает заказ
Ресторан -> Ресторан: Готовит блюдо
Ресторан -> Пользователь: Доставляет/выдаёт заказ
Пользователь -> Ресторан: Оплачивает заказ
Пользователь -> Ресторан: Оставляет отзыв
deactivate Ресторан

@enduml
