@startuml
title События доставки

actor "Курьер" as Courier
actor "Пользователь" as User

Courier -> Courier : Получает заказ (E1)
Courier -> Courier : Прокладывает маршрут (E2)
Courier -> User : Доставляет заказ (E3)
User -> User : Получает заказ (E4)

@enduml
