@startuml
title События заказа

actor "Пользователь" as User
participant "Ресторан" as Restaurant

User -> Restaurant : Делает заказ (E1)
activate Restaurant
Restaurant -> Restaurant : Получает заказ (E2)
Restaurant -> Restaurant : Готовит блюдо (E3)
Restaurant -> User : Заказ готов (E4)
deactivate Restaurant

@enduml
