@startuml
'Диаграмма деятельности — процесс доставки'
start
:Курьер получает заказ;
:Курьер собирает блюда;
if (Заказ с самовывозом?) then (Да)
 :Курьер ожидает клиента;
else (Нет)
 :Курьер прокладывает маршрут;
 :Курьер доставляет заказ;
endif
:Курьер отмечает выполнение заказа;
stop
@enduml
