@startuml
'Диаграмма классов — пользователи и роли'
abstract class Пользователь {
 -id : int
 -логин : String
 -пароль : String
}
class Клиент <<Пользователь>> {
 +сделатьЗаказ()
 +посмотретьИсториюЗаказа()
}
class Администратор <<Пользователь>> {
 +управлятьМеню()
 +анализироватьПродажи()
}
class Курьер <<Пользователь>> {
 +получитьЗаказ()
 +отметитьВыполнениеЗаказа()
}
Пользователь -->> Клиент : является
Пользователь -->> Администратор : является
Пользователь -->> Курьер : является
@enduml
