@startuml
'Диаграмма классов — система лояльности'
class Пользователь {
 -id : int
 -бонусныйБаланс : double
}
class Заказ {
 -id : int
 -сумма : double
}
class Акция {
 -id : int
 -название : String
 -условия : String
}
Пользователь -->> Заказ : делает
Заказ -->> Акция : участвует в
@enduml
