@startuml
entity Пользователь {
  id : int
  логин : String
  пароль : String
  бонусныйБаланс : double
}

entity Заказ {
  id : int
  идентификаторПользователя : int
  статус : String
  времяЗаказа : DateTime
  сумма : double
}

entity ПозицияЗаказа {
  id : int
  идентификаторЗаказа : int
  идентификаторБлюда : int
  количество : int
}

entity Блюдо {
  id : int
  название : String
  цена : double
  категория : String
}

Пользователь ||--o{ Заказ : "делает"
Заказ ||--|{ ПозицияЗаказа : "содержит"
ПозицияЗаказа }|--|| Блюдо : "относится к"
@enduml
