@startuml
'Диаграмма вариантов использования'
left to right direction
actor Пользователь
actor Администратор
actor Курьер
usecase "Сделать заказ" as UC1
usecase "Просмотреть меню" as UC2
usecase "Отслеживать заказ" as UC3
usecase "Управлять меню" as UC4
usecase "Анализировать продажи" as UC5
Пользователь -> UC1 : делает заказ
Пользователь -> UC2 : просматривает меню
Пользователь -> UC3 : отслеживает заказ
Администратор -> UC4 : управляет меню
Администратор -> UC5 : анализирует продажи
@enduml
